name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - faiss-cpu==1.7.4.post2  # version PyPI sans AVX2
      - flask
      - langchain
      - pdfplumber
      - openai
      - sentence-transformers
      - fastapi
      - uvicorn
      - PyMuPDF
      - python-dotenv
